steps:
- task: CopyFiles@2
  inputs:
    Contents: |
      main.tf
      secrets.json
    TargetFolder: '$(Build.BinariesDirectory)'
    CleanTargetFolder: true
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/tf.zip'
    replaceExistingArchive: true
    verbose: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/tf.zip'
    ArtifactName: 'terraformdrop'
    publishLocation: 'Container'